using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Breeds
{
    public class BreedSpellRelator
    {
        public static string FetchQuery = "SELECT * FROM breeds_spells";
    }

    [TableName("breeds_spells")]
    public class BreedSpell : IAutoGeneratedRecord
    {
        // Primitive properties

        public int Id
        {
            get;
            set;
        }

        public int Spell
        {
            get;
            set;
        }

        public int ObtainLevel
        {
            get;
            set;
        }

        public int BreedId
        {
            get;
            set;
        }

        public int VariantId
        {
            get;
            set;
        }

        public int VariantLevel
        {
            get;
            set;
        }
    }
}