using System;
using System.Collections.Generic;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Characters;
using Stump.Server.WorldServer.Database.Items;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Game.Effects.Instances;
using Stump.Server.WorldServer.Game.Items;

namespace Stump.Server.WorldServer.Database.Breeds
{
    public class BreedItemRelator
    {
        public static string FetchQuery = "SELECT * FROM breeds_items";
    }

    [TableName("breeds_items")]
    public class BreedItem : IAutoGeneratedRecord
    {
        // Primitive properties

        public int Id
        {
            get;
            set;
        }

        public int BreedId
        {
            get;
            set;
        }

        public int ItemId
        {
            get;
            set;
        }

        public uint Amount
        {
            get;
            set;
        }

        public bool MaxEffects
        {
            get;
            set;
        }

        public PlayerItemRecord GenerateItemRecord(CharacterRecord character)
        {
            var template = ItemManager.Instance.TryGetTemplate(ItemId);

            if (template == null)
            {
                throw new InvalidOperationException(string.Format("itemId {0} doesn't exists", ItemId));
            }

            List<EffectBase> effects = ItemManager.Instance.GenerateItemEffects(template, MaxEffects);

            var record = new PlayerItemRecord
                {
                    Id = PlayerItemRecord.PopNextId(),
                    OwnerId = character.Id,
                    Template = template,
                    Stack = Amount,
                    Position = CharacterInventoryPositionEnum.INVENTORY_POSITION_NOT_EQUIPED,
                    Effects = effects,
                };

            return record;
        }
    }
}