using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Jobs
{
    public class JobRecordRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_jobs";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM characters_jobs WHERE OwnerId={0}";
    }

    [TableName("characters_jobs")]
    public class JobRecord : IAutoGeneratedRecord
    {
        public int Id
        {
            get;
            set;
        }

        [Index]
        public int OwnerId
        {
            get;
            set;
        }

        public int TemplateId
        {
            get;
            set;
        }

        public long Experience
        {
            get;
            set;
        }

        public bool WorkForFree
        {
            get;
            set;
        }

        public int MinLevelCraftSetting
        {
            get;
            set;
        }
    }
}
