using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using Stump.Core.IO;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Game.Items;

namespace Stump.Server.WorldServer.Database.Jobs
{
    public static class RecipeRelator
    {
        public static string FetchQuery = "SELECT * FROM recipes";
    }

    [TableName("recipes")]
    [D2OClass("Recipe", "com.ankamagames.dofus.datacenter.jobs")]
    public class RecipeRecord : IAssignedByD2O, IAutoGeneratedRecord
    {
        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public ItemTemplate ItemTemplate => m_template ?? (m_template = ItemManager.Instance.TryGetTemplate(Id));

        public uint ResultNameId
        {

            get;
            set;
        }

        public uint ResultTypeId
        {

            get;
            set;
        }

        [D2OIgnore]
        public uint ResultLevel
        {

            get;
            set;
        }

        [Ignore]
        public int[] IngredientIds
        {
            get { return m_ingredientIds; }
            set
            {
                m_ingredientIds = value;
                m_ingredientIdsCSV = value.ToCSV(",");
            }
        }

        public ItemTemplate[] Ingredients
        {
            get { return m_ingredients ?? (m_ingredients = IngredientIds.Select(x => ItemManager.Instance.TryGetTemplate(x)).ToArray());}
        }

        private string m_ingredientIdsCSV;
        public string IngredientIdsCSV
        {
            get { return m_ingredientIdsCSV; }
            set
            {
                m_ingredientIdsCSV = value;
                m_ingredientIds = value.FromCSV<int>(",");
            }
        }

        [Ignore]
        public uint[] Quantities
        {
            get { return m_quantities; }
            set
            {
                m_quantities = value;
                m_quantitiesCSV = value.ToCSV(",");
            }
        }

        private string m_quantitiesCSV;
        private int[] m_ingredientIds;
        private uint[] m_quantities;
        private ItemTemplate m_template;
        private ItemTemplate[] m_ingredients;

        public string QuantitiesBin
        {
            get { return m_quantitiesCSV; }
            set
            {
                m_quantitiesCSV = value;
                m_quantities = value.FromCSV<uint>(",");
            }
        }

        public int JobId
        {
            get;
            set;
        }

        public int SkillId
        {
            get;
            set;
        }

        public virtual void BeforeSave(bool insert)
        {
            m_ingredientIdsCSV = m_ingredientIds.ToCSV(",");
            m_quantitiesCSV = m_quantities.ToCSV(",");

        }

        public void AssignFields(object obj)
        {
            var castedObj = (Recipe)obj;

            Id = castedObj.resultId;
            ResultNameId = castedObj.resultNameId;
            ResultTypeId = castedObj.resultTypeId;
            ResultLevel = castedObj.resultLevel;
            IngredientIds = castedObj.ingredientIds.ToArray();
            Quantities = castedObj.quantities.ToArray();
            JobId = castedObj.jobId;
            SkillId = castedObj.skillId;
        }
    }
}