using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Spells;

namespace Stump.Server.WorldServer.Database.Spells
{
    public class FinishMoveRelator
    {
        public static string FetchQuery = "SELECT * FROM finish_moves";
    }

    [TableName("finish_moves")]
    [D2OClass("FinishMove", "com.ankamagames.dofus.datacenter.spells")]
    public sealed class FinishMoveTemplate : IAssignedByD2O, IAutoGeneratedRecord
    {
        SpellLevelTemplate m_finishSpell;

        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public int Duration
        {
            get;
            set;
        }

        public bool Free
        {
            get;
            set;
        }

        public uint NameId
        {
            get;
            set;
        }

        public int Category
        {
            get;
            set;
        }

        public int SpellLevel
        {
            get;
            set;
        }

        public SpellLevelTemplate FinishSpell => m_finishSpell ??
                       (m_finishSpell = SpellManager.Instance.GetSpellLevel(SpellLevel));

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var finishMove = (DofusProtocol.D2oClasses.FinishMove)d2oObject;
            Id = finishMove.id;
            Duration = finishMove.duration;
            Free = finishMove.free;
            NameId = finishMove.nameId;
            Category = finishMove.category;
            SpellLevel = finishMove.spellLevel;
        }

        #endregion
    }
}