using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Spells
{
    public class SpellEffectFixRelator
    {
        public static string FetchQuery = "SELECT * FROM spells_effects_fix";

    }

    [TableName("spells_effects_fix")]
    public class SpellEffectFix : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        public int? SpellId
        {
            get;
            set;
        }

        public int? SpellLevelId
        {
            get;
            set;
        }

        public int? EffectId
        {
            get;
            set;
        }

        public int? EffectIndex
        {
            get;
            set;
        }

        public int? TriggerBuffDuration
        {
            get;
            set;
        }

        public int? Dispellable
        {
            get;
            set;
        }

        public int? ActionId
        {
            get;
            set;
        }

        public int? ClientEffectId
        {
            get;
            set;
        }

        public int? Priority
        {
            get;
            set;
        }
    }
}