using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.DofusProtocol.D2oClasses;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Spells;

namespace Stump.Server.WorldServer.Database.Spells
{
    public class SpellBombRelator
    {
        public static string FetchQuery = "SELECT * FROM spells_bombs";
    }

    [TableName("spells_bombs")]
    [D2OClass("SpellBomb", "com.ankamagames.dofus.datacenter.spells")]
    public sealed class SpellBombTemplate : IAssignedByD2O, IAutoGeneratedRecord
    {
        SpellTemplate m_chainReactionSpell;
        SpellTemplate m_explodReactionSpell;
        SpellTemplate m_instantReactionSpell;

        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public int ChainReactionSpellId
        {
            get;
            set;
        }

        public SpellTemplate ChainReactionSpell => m_chainReactionSpell ??
                       (m_chainReactionSpell = SpellManager.Instance.GetSpellTemplate(ChainReactionSpellId));

        public int ExplodSpellId
        {
            get;
            set;
        }
        public SpellTemplate ExplodReactionSpell => m_explodReactionSpell ??
                       (m_explodReactionSpell = SpellManager.Instance.GetSpellTemplate(ExplodSpellId));

        public int WallId
        {
            get;
            set;
        }

        public int InstantSpellId
        {
            get;
            set;
        }
        public SpellTemplate InstantReactionSpell => m_instantReactionSpell ??
                       (m_instantReactionSpell = SpellManager.Instance.GetSpellTemplate(InstantSpellId));

        public int ComboCoeff
        {
            get;
            set;
        }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var spell = (SpellBomb) d2oObject;
            Id = spell.id;
            ChainReactionSpellId = spell.chainReactionSpellId;
            ExplodSpellId = spell.explodSpellId;
            WallId = spell.wallId;
            InstantSpellId = spell.instantSpellId;
            ComboCoeff = spell.comboCoeff;
        }

        #endregion
    }
}