using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.DofusProtocol.D2oClasses;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Spells
{
    public class SpellTypeRelator
    {
        public static string FetchQuery = "SELECT * FROM spells_types";
    }

    [TableName("spells_types")]
    [D2OClass("SpellType", "com.ankamagames.dofus.datacenter.spells")]
    public sealed class SpellType : IAssignedByD2O, IAutoGeneratedRecord
    {
        private string m_name;
        private string m_shortName;

        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public uint LongNameId
        {
            get;
            set;
        }

        public string LongName
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(LongNameId)); }
        }

        public uint ShortNameId
        {
            get;
            set;
        }

        public string ShortName
        {
            get { return m_shortName ?? (m_shortName = TextManager.Instance.GetText(ShortNameId)); }
        }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var type = (DofusProtocol.D2oClasses.SpellType) d2oObject;
            Id = type.id;
            LongNameId = type.longNameId;
            ShortNameId = type.shortNameId;
        }

        #endregion
    }
}