using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Accounts
{
    public class AccountRelationRelator
    {
        public static string FetchQuery = "SELECT * FROM accounts_relations";
        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByAccount = "SELECT * FROM accounts_relations WHERE AccountId={0}";
    }

    [TableName("accounts_relations")]
    public class AccountRelation : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        public AccountRelationType Type
        {
            get;
            set;
        }

        [Index]
        public int AccountId
        {
            get;
            set;
        }

        public int TargetId
        {
            get;
            set;
        }
    }

    public enum AccountRelationType
    {
        Friend,
        Ignored
    }
}