using System;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Guilds
{
    public class EmblemRelator
    {
        public static string FetchQuery = "SELECT * FROM guilds_emblems";
    }

    [TableName("guilds_emblems")]
    [D2OClass("EmblemSymbol", "com.ankamagames.dofus.datacenter.guild")]
    public class EmblemRecord : IAssignedByD2O, IAutoGeneratedRecord
    {
        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public int IconId
        {
            get;
            set;
        }

        public int SkinId
        {
            get;
            set;
        }

        public int Order
        {
            get;
            set;
        }

        public int CategoryId
        {
            get;
            set;
        }

        public Boolean Colorizable
        {
            get;
            set;
        }

        public void AssignFields(object d2oObject)
        {
            var emblem = (EmblemSymbol) d2oObject;
            Id = emblem.Id;
            IconId = emblem.IconId;
            SkinId = emblem.SkinId;
            Order = emblem.Order;
            CategoryId = emblem.CategoryId;
            Colorizable = emblem.Colorizable;
        }
    }
}