using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Spells;

namespace Stump.Server.WorldServer.Database.Characters
{
    public class CharacterSpellRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_spells";
        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM characters_spells WHERE OwnerId={0}";
    }

    [TableName("characters_spells")]
    public class CharacterSpellRecord : ISpellRecord, IAutoGeneratedRecord
    {
        // Primitive properties

        public int Id
        {
            get;
            set;
        }

        [Index]
        public int OwnerId
        {
            get;
            set;
        }

        public short Position
        {
            get;
            set;
        }

        #region ISpellRecord Members

        public int SpellId
        {
            get;
            set;
        }

        public short Level
        {
            get;
            set;
        }

        #endregion

        public override string ToString()
        {
            return (SpellIdEnum) SpellId + " (" + SpellId + ")";
        }
    }
}