using System;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Accounts
{
    public class CharactersMiniGamesRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_mini_games";
        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchById = "SELECT * FROM characters_mini_games WHERE CharacterId={0}";
    }

    [TableName("characters_mini_games")]
    public class CharactersMiniGames : IAutoGeneratedRecord
    {
        public CharactersMiniGames()
        {
        }

        [Index]
        [PrimaryKey("CharacterId", false)]
        public int CharacterId
        {
            get;
            set;
        }

        public DateTime Hammer
        {
            get;
            set;
        }
    }
}