using System.Collections.Generic;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Startup
{
    public class StartupActionRecordRelator
    {
        public static string FetchQuery = "SELECT * FROM startup_actions " +
                                          "LEFT JOIN startup_actions_items_binds ON startup_actions_items_binds.StartupActionId = startup_actions.Id " +
                                          "LEFT JOIN startup_actions_items ON startup_actions_items.Id = startup_actions_items_binds.ItemId";
    }

    /// <summary>
    /// Only used for many to many relation
    /// </summary>
    [TableName("startup_actions_items_binds")]
    public class StartupActionRecordItems
    {
        [PrimaryKey("StartupActionId")]
        public int StartupActionId
        {
            get;
            set;
        }

        [PrimaryKey("ItemId")]
        public int ItemId
        {
            get;
            set;
        }
    }

    [TableName("startup_actions")]
    public sealed class StartupActionRecord : IAutoGeneratedRecord
    {
        private List<StartupActionItemRecord> m_items;

        public int Id
        {
            get;
            set;
        }

        public string Title
        {
            get;
            set;
        }

        public string Text
        {
            get;
            set;
        }

        public string DescUrl
        {
            get;
            set;
        }

        public string PictureUrl
        {
            get;
            set;
        }

        [Ignore]
        public List<StartupActionItemRecord> Items
        {
            get { return m_items ?? new List<StartupActionItemRecord>(); }
            set { m_items = value; }
        }
    }
}