using Stump.ORM;
using Stump.Core.IO;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System.Linq;
using System.Collections.Generic;

namespace Stump.Server.WorldServer.Database.Companion
{
    [TableName("companions")]
    public class CompanionRecord : IAutoGeneratedRecord
    {
        List<int> m_spells = new List<int>();
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }
        public int ItemId
        {
            get;
            set;
        }
        public string Look
        {
            get;
            set;
        }
        public int StartingSpellLevelId
        {
            get;
            set;
        }
        [NullString]
        public string Characterisitcs
        {
            get;
            set;
        }
        [NullString]
        public string Spells
        {
            get
            {
                return m_spells.ToCSV(",");
            }
            set
            {
                m_spells = value.FromCSV<int>(",").ToList();
            }
        }
        [NullString]
        public string BoneId
        {
            get;
            set;

        }
        [Ignore]
        public List<int> SpellsId
        {
            get
            {
                return m_spells;
            }
            set
            {
                m_spells = value;
            }
        }



    }
}
