using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Characters;

namespace Stump.Server.WorldServer.Database.Shortcuts
{
    public class PresetShortcutRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_shortcuts_items_presets";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM characters_shortcuts_items_presets WHERE OwnerId={0}";
    }

    [TableName("characters_shortcuts_items_presets")]
    public class PresetShortcut : Shortcut, IAutoGeneratedRecord
    {
        public PresetShortcut()
        {
        }

        public PresetShortcut(CharacterRecord owner, int slot, int presetId)
            : base(owner, slot)
        {
            PresetId = presetId;
        }

        private int m_presetId;

        public int PresetId
        {
            get { return m_presetId; }
            set
            {
                m_presetId = value;
                IsDirty = true;
            }
        }

        public override DofusProtocol.Types.Shortcut GetNetworkShortcut()
        {
            return new ShortcutObjectPreset((sbyte)Slot, (sbyte)PresetId);
        }
    }
}
