using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.World
{
    public class WorldMapScrollActionRelator
    {
        public static string FetchQuery = "SELECT * FROM world_maps_scroll_actions";
    }

    [TableName("world_maps_scroll_actions")]
    class WorldMapScrollActionRecord : IAutoGeneratedRecord
    {
        public int Id
        {
            get;
            set;
        }

        public string RightExists
        {
            get;
            set;
        }

        public string BottomExists
        {
            get;
            set;
        }

        public string LeftExists
        {
            get;
            set;
        }

        public string TopExists
        {
            get;
            set;
        }

        public int RightMapId
        {
            get;
            set;
        }

        public int BottomMapId
        {
            get;
            set;
        }

        public int LeftMapId
        {
            get;
            set;
        }

        public int TopMapId
        {
            get;
            set;
        }
    }
}
