namespace Stump.Server.WorldServer.Database.World
{
    using Stump.ORM;
    using Stump.ORM.SubSonic.SQLGeneration.Schema;
    using Stump.Server.WorldServer.Game.Maps;

    namespace Database.World
    {
        public class WorldMapGraveyardRelator
        {
            public static string FetchQuery = "SELECT * FROM world_maps_graveyard";
        }

        [TableName("world_maps_graveyard")]
        public sealed class WorldMapGraveyardRecord : IAutoGeneratedRecord
        {
            [PrimaryKey("Id")]
            public int Id
            {
                get;
                set;
            }

            public int MapId
            {
                get;
                set;
            }

            public int CellId
            {
                get;
                set;
            }

            public int SubAreaId
            {
                get;
                set;
            }

            public int PhoenixMapId
            {
                get;
                set;
            }

            [Ignore]
            public Map Map => Game.World.Instance.GetMap(MapId);
        }
    }

}
