using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Ranks
{
    public class RankRewardRelator
    {
        public static string FetchQuery = "SELECT * FROM ranks_rewards";
    }

    [TableName("ranks_rewards")]
    class RankRewardEntry : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        public int RankId
        {
            get;
            set;
        }

        public string Type
        {
            get;
            set;
        }

        public string Optional1
        {
            get;
            set;
        }

        public string Optional2
        {
            get;
            set;
        }

        public string Optional3
        {
            get;
            set;
        }
    }
}