using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Characters
{
    public class RankTableRelator
    {
        public static string FetchQuery = "SELECT * FROM ranks";
    }

    [TableName("ranks")]
    class RankTableEntry : IAutoGeneratedRecord
    {
        [PrimaryKey("RankId")]
        public int RankId
        {
            get;
            set;
        }

        public string RankName
        {
            get;
            set;
        }

        public int RankExp
        {
            get;
            set;
        }

        public int RankBonus
        {
            get;
            set;
        }
    }
}
