using System;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Dopple
{
    [TableName("characters_dopple")]
    public class DoppleRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id", false)]
        public int CharacterId { get; set; }
        public int DopeulId { get; set; }
        public DateTime Time { get; set; }
        public string Ip { get; set; }
        [Ignore]
        public bool IsNew { get; set; }
        [Ignore]
        public bool IsUpdated { get; set; }
    }
}