using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Social
{
    public class BadWordRelator
    {
        public static string FetchQuery = "SELECT * FROM bad_words";
    }

    [TableName("bad_words")]
    public sealed class BadWordRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        public string Text
        {
            get;
            set;
        }

        [Ignore]
        public bool IsDirty
        {
            get;
            set;
        }

        [Ignore]
        public bool IsNew
        {
            get;
            set;
        }
    }
}