using System;
using System.Linq;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Items.Templates
{
    public class ItemTypeRecordRelator
    {
        public static string FetchQuery = "SELECT * FROM items_types";
    }

    [TableName("items_types")]
    [D2OClass("ItemType", "com.ankamagames.dofus.datacenter.items")]
    public sealed class ItemTypeRecord : IAssignedByD2O, IAutoGeneratedRecord
    {
        private string m_name;

        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public ItemTypeEnum ItemType
        {
            get { return (ItemTypeEnum) Id; }
        }

        public uint NameId
        {
            get;
            set;
        }

        public string Name
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(NameId)); }
        }

        public uint SuperTypeId
        {
            get;
            set;
        }

        public ItemSuperTypeEnum SuperType
        {
            get { return (ItemSuperTypeEnum) SuperTypeId; }
        }

        public Boolean Plural
        {
            get;
            set;
        }

        public uint Gender
        {
            get;
            set;
        }

        public uint ZoneMinSize
        {
            get;
            set;
        }

        public uint ZoneSize
        {
            get;
            set;
        }

        public uint ZoneEfficiencyPercent
        {
            get;
            set;
        }

        public uint ZoneMaxEfficiency
        {
            get;
            set;
        }

        public SpellShapeEnum ZoneShape
        {
            get;
            set;
        }

        public Boolean Mimickable
        {
            get;
            set;
        }

        public int CraftXpRatio
        {
            get;
            set;
        }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var type = (ItemType) d2oObject;
            Id = type.id;
            NameId = type.nameId;
            SuperTypeId = type.superTypeId;
            Plural = type.plural;
            Gender = type.gender;
            ParseRawZone(type.rawZone);
            Mimickable = type.mimickable;
            CraftXpRatio = type.craftXpRatio;
        }

        #endregion

        private void ParseRawZone(string rawZone)
        {
            if (string.IsNullOrEmpty(rawZone) || rawZone == "null")
            {
                ZoneMinSize = 0;
                ZoneSize = 0;
                ZoneShape = 0;
                ZoneEfficiencyPercent = 0;
                ZoneMaxEfficiency = 0;
                return;
            }

            var chr = rawZone[0];
            SpellShapeEnum shape;
            switch (chr)
            {
                case '+':
                    shape = SpellShapeEnum.plus;
                    break;
                case '-':
                    shape = SpellShapeEnum.minus;
                    break;
                case '/':
                    shape = SpellShapeEnum.slash;
                    break;
                case '*':
                    shape = SpellShapeEnum.star;
                    break;
                case '#':
                    shape = SpellShapeEnum.sharp;
                    break;
                default:
                    shape = (SpellShapeEnum) Enum.Parse(typeof (SpellShapeEnum), chr.ToString());
                    break;
            }
            ZoneShape = shape;

            var zone = rawZone.Substring(1).Split(',');
            var efficiencyZone = ZoneShape == SpellShapeEnum.C || ZoneShape == SpellShapeEnum.X || ZoneShape == SpellShapeEnum.Q || ZoneShape == SpellShapeEnum.plus || ZoneShape == SpellShapeEnum.sharp;

            var totalZone = zone.Count(x => !string.IsNullOrEmpty(x));
            switch (totalZone)
            {
                case 1:
                    ZoneSize = uint.Parse(zone[0]);
                    break;
                case 2:
                    ZoneSize = uint.Parse(zone[0]);
                    if (efficiencyZone)
                    {
                        ZoneMinSize = uint.Parse(zone[1]);
                    }
                    else
                    {
                        ZoneEfficiencyPercent = uint.Parse(zone[1]);
                    }
                    break;
                case 3:
                    ZoneSize = uint.Parse(zone[0]);
                    if (efficiencyZone)
                    {
                        ZoneMinSize = uint.Parse(zone[1]);
                        ZoneEfficiencyPercent = uint.Parse(zone[2]);
                    }
                    else
                    {
                        ZoneEfficiencyPercent = uint.Parse(zone[1]);
                        ZoneMaxEfficiency = uint.Parse(zone[2]);
                    }
                    break;
                case 4:
                    ZoneSize = uint.Parse(zone[0]);
                    ZoneMinSize = uint.Parse(zone[1]);
                    ZoneEfficiencyPercent = uint.Parse(zone[2]);
                    ZoneMaxEfficiency = uint.Parse(zone[3]);
                    break;
                default:
                    ZoneMinSize = 0;
                    ZoneSize = 0;
                    ZoneEfficiencyPercent = 0;
                    ZoneMaxEfficiency = 0;
                    break;
            }
        }
    }
}