using Stump.ORM;
using Stump.ORM.Relator;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Mounts
{
    public class MountBonusRelator
    {
        public static string FecthQuery = "SELECT * FROM mounts_bonus";
    }
    
    [TableName("mounts_bonus")]
    public class MountBonus : IAutoGeneratedRecord, IJoined
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        public int MountTemplateId
        {
            get;
            set;
        }
        
        int IJoined.JoinedId => MountTemplateId;

        public int EffectId
        {
            get;
            set;
        }

        public int Amount
        {
            get;
            set;
        }
    }
}