using Stump.DofusProtocol.D2oClasses;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Arena
{
    public class ArenaLeagueSeasonRelator
    {
        public static string FetchQuery = "SELECT * FROM arena_leagues_seasons";
    }

    [TableName("arena_leagues_seasons")]
    public class ArenaLeagueSeason : IAssignedByD2O, IAutoGeneratedRecord
    {
        [PrimaryKey("Id", autoIncrement: true)]
        public int Id
        {
            get;
            set;
        }

        public int SeasonId
        {
            get;
            set;
        }

        public uint NameId
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }

        public void AssignFields(object obj)
        {
            var season = (DofusProtocol.D2oClasses.ArenaLeagueSeason)obj;
            SeasonId = season.Id;
            NameId = season.NameId;
        }
    }
}
