using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items.Usables
{
    public class TeleportPotionRelator
    {
        public static string FetchQuery = "SELECT * FROM items_teleport_potions";
    }

    [TableName("items_teleport_potions")]
    public class TeleportPotionRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("ItemId", false)]
        public int ItemId
        {
            get;
            set;
        }

        public int MapId
        {
            get;
            set;
        }

        public int CellId
        {
            get;
            set;
        }

        public int? Orientation
        {
            get;
            set;
        }
    }
}