using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items
{

    public class MountItemRelator
    {
        public static string FetchQuery = "SELECT * FROM mounts_items";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM mounts_items WHERE MountId={0}";
    }

    [TableName("mounts_items")]
    public class MountItemRecord : ItemRecord<MountItemRecord>, IAutoGeneratedRecord
    {
        public MountItemRecord()
        {

        }

        private int m_mountId;

        [Index]
        public int MountId
        {
            get { return m_mountId; }
            set
            {
                m_mountId = value;
                IsDirty = true;
            }
        }

        [PrimaryKey("Id", false)]
        public override int Id
        {
            get;
            set;
        }
    }
}