//using System.Collections.Generic;
//using System.IO;
//using System.Linq;
//using Stump.DofusProtocol.Enums;
//using Stump.DofusProtocol.Types;
//using Stump.ORM;
//using Stump.ORM.SubSonic.SQLGeneration.Schema;

//namespace Stump.Server.WorldServer.Database.Items
//{
//    public class PlayerPresetRelator
//    {
//        public static string FetchQuery = "SELECT * FROM characters_items_presets";

//        /// <summary>
//        /// Use string.Format
//        /// </summary>
//        public static string FetchByOwner = "SELECT * FROM characters_items_presets WHERE OwnerId={0}";
//    }

//    [TableName("characters_items_presets")]
//    public class PlayerPresetRecord : ISaveIntercepter, IAutoGeneratedRecord
//    {
//        public bool IsDirty;
//        public bool IsNew;

//        [PrimaryKey("Id")]
//        public int Id
//        {
//            get;
//            set;
//        }

//        int m_presetId;

//        public int PresetId
//        {
//            get { return m_presetId; }
//            set
//            {
//                m_presetId = value;
//                IsDirty = true;
//            }
//        }

//        int m_ownerId;

//        [Index]
//        public int OwnerId
//        {
//            get { return m_ownerId; }
//            set
//            {
//                m_ownerId = value;
//                IsDirty = true;
//            }
//        }

//        int m_symbolId;

//        public int SymbolId
//        {
//            get { return m_symbolId; }
//            set
//            {
//                m_symbolId = value;
//                IsDirty = true;
//            }
//        }

//        [Ignore]
//        public List<ItemForPreset> Objects
//        {
//            get;
//            set;
//        }

//        byte[] m_serializedObjects;

//        public byte[] SerializedObjects
//        {
//            get { return m_serializedObjects; }
//            set
//            {
//                m_serializedObjects = value;
//                Objects = Deserialize(value);
//                IsDirty = true;
//            }
//        }

//        public void AddObject(ItemForPreset presetItem)
//        {
//            Objects.Add(presetItem);
//            IsDirty = true;
//        }

//        public void RemoveObject(ItemForPreset presetItem)
//        {
//            Objects.Remove(presetItem);
//            IsDirty = true;
//        }

//        public void RemoveObject(int presetItemId)
//        {
//            Objects.RemoveAll(x => x.objUid == presetItemId);
//            IsDirty = true;
//        }

//        public ItemForPreset GetPresetItem(int itemGuid) => Objects.FirstOrDefault(x => x.objUid == itemGuid);

//        public void BeforeSave(bool insert)
//        {
//            m_serializedObjects = Serialize();
//        }

//        public Preset GetNetworkPreset() => new Preset((short)PresetId);

//        byte[] Serialize()
//        {
//            var buffer = new List<byte>();

//            foreach (var preset in Objects)
//            {
//                var writer = new BinaryWriter(new MemoryStream());

//                writer.Write(preset.objUid);
//                writer.Write(preset.objGid);
//                writer.Write(preset.position);

//                buffer.AddRange(((MemoryStream)writer.BaseStream).ToArray());
//            }

//            return buffer.ToArray();
//        }

//        static List<ItemForPreset> Deserialize(byte[] buffer)
//        {
//            var presetObjects = new List<ItemForPreset>();

//            var reader = new BinaryReader(new MemoryStream(buffer, 0, buffer.Length));

//            while (reader.BaseStream.Position < buffer.Length)
//            {
//                var objUid = reader.ReadInt32();
//                var objGid = reader.ReadInt16();
//                var position = reader.ReadByte();

//                presetObjects.Add(new ItemForPreset((sbyte)position, (ushort)objGid, (uint)objUid));
//            }

//            return presetObjects.ToList();
//        }
//    }
//}
