using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items
{
    public class TaxCollectorItemRelator
    {
        public static string FetchQuery = "SELECT * FROM taxcollectors_items";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM taxcollectors_items WHERE OwnerId={0}";
    }

    [TableName("taxcollectors_items")]
    public class TaxCollectorItemRecord : ItemRecord<TaxCollectorItemRecord>, IAutoGeneratedRecord
    {
        private int m_ownerId;

        public int OwnerId
        {
            get { return m_ownerId; }
            set
            {
                m_ownerId = value;
                IsDirty = true;
            }
        }
    }
}
