using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.DofusProtocol.D2oClasses;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Monsters
{
    public class MonsterSuperRaceRelator
    {
        public static string FetchQuery = "SELECT * FROM monsters_superraces";
    }

    [TableName("monsters_superraces")]
    [D2OClass("MonsterSuperRace", "com.ankamagames.dofus.datacenter.monsters")]
    public sealed class MonsterSuperRace : IAssignedByD2O, IAutoGeneratedRecord
    {
        private string m_name;

        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public uint NameId
        {
            get;
            set;
        }

        public string Name
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(NameId)); }
        }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var race = (DofusProtocol.D2oClasses.MonsterSuperRace) d2oObject;
            Id = race.id;
            NameId = race.nameId;
        }

        #endregion
    }
}