using Stump.Core.IO;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Maps;
using System.Collections.Generic;
using System.Linq;

namespace Stump.Server.WorldServer.Database.Monsters
{
    public class MonsterNaniRelator
    {
        public static string FetchQuery = "SELECT * FROM monsters_nani";
    }

    [TableName("monsters_nani")]
    public class MonsterNaniRecord : IAutoGeneratedRecord
    {
        private string m_subAreasCSV;
        public int Id
        {
            get;
            set;
        }

        public int MonsterGradeId
        {
            get;
            set;
        }

        public string SubAreasCSV
        {
            get { return m_subAreasCSV; }
            set { m_subAreasCSV = value; }
        }

        [Ignore]
        public SubArea[] SubAreas
        {
            get
            {
                List<SubArea> list = new List<SubArea>();
                foreach(var id in m_subAreasCSV.FromCSV<int>(";"))
                {
                    var subarea = Game.World.Instance.GetSubArea(id);
                    if (subarea != null) list.Add(subarea);
                }
                return list.ToArray();
            }
            set
            {
                m_subAreasCSV = value.Select(x => x.Id).ToCSV(";");
            }
        }
    }
}