using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;
using Stump.Server.WorldServer.Game.Actors.RolePlay.Monsters;

namespace Stump.Server.WorldServer.Database.Monsters
{
    public class MonsterRaceRelator
    {
        public static string FetchQuery = "SELECT * FROM monsters_races";
    }

    [TableName("monsters_races")]
    [D2OClass("MonsterRace", "com.ankamagames.dofus.datacenter.monsters")]
    public class MonsterRace : IAssignedByD2O, IAutoGeneratedRecord
    {
        private string m_name;
        private MonsterSuperRace m_superRace;

        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public int SuperRaceId
        {
            get;
            set;
        }

        [Ignore]
        public MonsterSuperRace SuperRace
        {
            get { return m_superRace ?? (m_superRace = MonsterManager.Instance.GetMonsterSuperRace(SuperRaceId)); }
            set
            {
                m_superRace = value;
                SuperRaceId = value.Id;
            }
        }

        public uint NameId
        {
            get;
            set;
        }

        public string Name
        {
            get { return m_name ?? (m_name = TextManager.Instance.GetText(NameId)); }
        }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var race = (DofusProtocol.D2oClasses.MonsterRace) d2oObject;
            Id = race.id;
            NameId = race.nameId;
            SuperRaceId = race.superRaceId;
        }

        #endregion
    }
}