using System;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items.BidHouse
{
    public class BidHouseItemRelator
    {
        public static string FetchQuery = "SELECT * FROM bidhouse_items";

        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM bidhouse_items WHERE OwnerId={0}";
    }

    [TableName("bidhouse_items")]
    public class BidHouseItemRecord : ItemRecord<BidHouseItemRecord>, IAutoGeneratedRecord
    {
        private int m_ownerId;

        public int OwnerId
        {
            get { return m_ownerId; }
            set
            {
                m_ownerId = value;
                IsDirty = true;
            }
        }

        private long m_price;

        public long Price
        {
            get { return m_price; }
            set
            {
                m_price = value;
                IsDirty = true;
            }
        }

        private bool m_sold;

        public bool Sold
        {
            get { return m_sold; }
            set
            {
                m_sold = value;
                IsDirty = true;
            }
        }

        private DateTime m_sellDate;

        public DateTime SellDate
        {
            get { return m_sellDate; }
            set
            {
                m_sellDate = value;
                IsDirty = true;
            }
        }
    }
}
