using Stump.Core.IO;
using Stump.Core.Reflection;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Achievements;

namespace Stump.Server.WorldServer.Database.Achievements
{
    [D2OClass("AchievementReward", "com.ankamagames.dofus.datacenter.quest", true), TableName("achievements_rewards")]
    public class AchievementRewardRecord : IAutoGeneratedRecord, ISaveIntercepter, IAssignedByD2O
    {
        // FIELDS
        private uint[] m_itemsReward;
        private uint[] m_itemsQuantityReward;
        private uint[] m_emotesReward;
        private uint[] m_spellsReward;
        private uint[] m_titlesReward;
        private uint[] m_ornamentsReward;
        private string m_itemsRewardCSV;
        private string m_itemsQuantityRewardCSV;
        private string m_emotesRewardCSV;
        private string m_spellsRewardCSV;
        private string m_titlesRewardCSV;
        private string m_ornamentsRewardCSV;
        private AchievementTemplate m_achievement;

        // PROPERTIES
        [PrimaryKey("Id", false)]
        public uint Id
        {
            get;
            set;
        }
        public uint AchievementId
        {
            get;
            set;
        }
        [Ignore]
        public AchievementTemplate Achievement
        {
            get
            {
                if (this.m_achievement == null)
                {
                    this.m_achievement = Singleton<AchievementManager>.Instance.TryGetAchievement(this.AchievementId);
                }

                return this.m_achievement;
            }
        }
        public int LevelMin
        {
            get;
            set;
        }
        public int LevelMax
        {
            get;
            set;
        }
        [Ignore]
        public uint[] ItemsReward
        {
            get
            {
                return this.m_itemsReward;
            }
            set
            {
                this.m_itemsReward = value;
                this.m_itemsRewardCSV = value.ToCSV(",");
            }
        }
        public string ItemsRewardCSV
        {
            get
            {
                return this.m_itemsRewardCSV;
            }
            set
            {
                this.m_itemsRewardCSV = value;
                this.m_itemsReward = value.FromCSV<uint>(",");
            }
        }
        [Ignore]
        public uint[] ItemsQuantityReward
        {
            get
            {
                return this.m_itemsQuantityReward;
            }
            set
            {
                this.m_itemsQuantityReward = value;
                this.m_itemsQuantityRewardCSV = value.ToCSV(",");
            }
        }
        public string ItemsQuantityRewardCSV
        {
            get
            {
                return this.m_itemsQuantityRewardCSV;
            }
            set
            {
                this.m_itemsQuantityRewardCSV = value;
                this.m_itemsQuantityReward = value.FromCSV<uint>(",");
            }
        }
        [Ignore]
        public uint[] EmotesReward
        {
            get
            {
                return this.m_emotesReward;
            }
            set
            {
                this.m_emotesReward = value;
                this.m_emotesRewardCSV = value.ToCSV(",");
            }
        }
        public string EmotesRewardCSV
        {
            get
            {
                return this.m_emotesRewardCSV;
            }
            set
            {
                this.m_emotesRewardCSV = value;
                this.m_emotesReward = value.FromCSV<uint>(",");
            }
        }
        [Ignore]
        public uint[] SpellsReward
        {
            get
            {
                return this.m_spellsReward;
            }
            set
            {
                this.m_spellsReward = value;
                this.m_spellsRewardCSV = value.ToCSV(",");
            }
        }
        public string SpellsRewardCSV
        {
            get
            {
                return this.m_spellsRewardCSV;
            }
            set
            {
                this.m_spellsRewardCSV = value;
                this.m_spellsReward = value.FromCSV<uint>(",");
            }
        }
        [Ignore]
        public uint[] TitlesReward
        {
            get
            {
                return this.m_titlesReward;
            }
            set
            {
                this.m_titlesReward = value;
                this.m_titlesRewardCSV = value.ToCSV(",");
            }
        }
        public string TitlesRewardCSV
        {
            get
            {
                return this.m_titlesRewardCSV;
            }
            set
            {
                this.m_titlesRewardCSV = value;
                this.m_titlesReward = value.FromCSV<uint>(",");
            }
        }
        [Ignore]
        public uint[] OrnamentsReward
        {
            get
            {
                return this.m_ornamentsReward;
            }
            set
            {
                this.m_ornamentsReward = value;
                this.m_ornamentsRewardCSV = value.ToCSV(",");
            }
        }
        public string OrnamentsRewardCSV
        {
            get
            {
                return this.m_ornamentsRewardCSV;
            }
            set
            {
                this.m_ornamentsRewardCSV = value;
                this.m_ornamentsReward = value.FromCSV<uint>(",");
            }
        }

        // CONSTRUCTORS

        // METHODS
        public void BeforeSave(bool insert)
        {

        }

        public virtual void AssignFields(object d2oObject)
        {
            var item = (AchievementReward)d2oObject;
            this.Id = (uint)item.id;
            this.AchievementId = item.achievementId;
            this.ItemsReward = item.itemsReward.ToArray();
            this.ItemsQuantityReward = item.itemsQuantityReward.ToArray();
            this.EmotesReward = item.emotesReward.ToArray();
            this.SpellsReward = item.spellsReward.ToArray();
            this.TitlesReward = item.titlesReward.ToArray();
            this.OrnamentsReward = item.ornamentsReward.ToArray();
        }
    }

}
