using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Spells;

namespace Stump.Server.WorldServer.Database.AI
{
    public class InitBrainRelator
    {
        public const string FetchQuery = "SELECT * FROM ai_init_brains";
    }

    [TableName("ai_init_brains")]
    public class InitBrainRecord : IAutoGeneratedRecord
    {
        private Spell m_spell;

        [PrimaryKey("Id", false)]
        public int MonsterId
        {
            get;
            set;
        }

        public int SpellId
        {
            get;
            set;
        }

        public byte Level
        {
            get;
            set;
        }

        [Ignore]
        public Spell Spell
        {
            get { return m_spell ?? (m_spell = new Spell(SpellId, Level)); }
        }
    }
}
