using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Game.Items;

namespace Stump.Server.WorldServer.Database.Dungeon
{
    public class DungeonItemsRelator
    {
        public static string FetchQuery = "SELECT * FROM items_dungeons";
    }

    [TableName("items_dungeons")]
    public class DungeonItemsRecord : IAutoGeneratedRecord
    {
        private ItemTemplate m_template;

        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        public ItemTemplate ItemTemplate => m_template ?? (m_template = ItemManager.Instance.TryGetTemplate(ItemId));

        public int ItemId
        {
            get;
            set;
        }

    }
}