using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.DofusProtocol.D2oClasses;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.World.Maps
{
    public class MapReferenceRecordRelator
    {
        public static string FetchQuery = "SELECT * FROM world_maps_references";
    }

    [TableName("world_maps_references")]
    [D2OClass("MapReference", "com.ankamagames.dofus.datacenter.world")]
    public sealed class MapReferenceRecord : IAssignedByD2O, IAutoGeneratedRecord
    {
        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }

        public uint MapId
        {
            get;
            set;
        }

        public int CellId
        {
            get;
            set;
        }

        #region IAssignedByD2O Members

        public void AssignFields(object d2oObject)
        {
            var map = (MapReference) d2oObject;
            Id = map.id;
            MapId = (uint)map.mapId;
            CellId = map.cellId;
        }

        #endregion
    }
}