using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.HavenBags
{
    public class HavenBagRelator
    {
        public static string FetchQuery = "SELECT * FROM havenbags";
    }

    [TableName("havenbags")]
    public class HavenBagRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        [Index]
        public int HavenBagId
        {
            get;
            set;
        }

        public int OwnerId
        {
            get;
            set;
        }

        public sbyte ThemeId
        {
            get;
            set;
        }

        public sbyte MaxRoom
        {
            get;
            set;
        }

        public sbyte RoomId
        {
            get;
            set;
        }

        public bool FriendsAllowed
        {
            get;
            set;
        }

        public bool GuildAllowed
        {
            get;
            set;
        }
    }
}