using System.Collections.Generic;
using Stump.ORM;
using Stump.ORM.Relator;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Quests
{
    public class QuestRecordRelator : OneToManyRelator<QuestRecord, QuestObjectiveStatus>
    {
        public static string FetchByOwner = "SELECT * FROM characters_quests WHERE characters_quests.OwnerId = {0}";
        public static string FetchObjectiveByOwner = "SELECT * FROM characters_quests_objectives WHERE characters_quests_objectives.OwnerId = {0}";
    }

    [TableName("characters_quests")]
    public class QuestRecord : IOneToManyRecord1<QuestObjectiveStatus>, IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        int IJoined.JoinedId => Id;

        [Index]
        public int OwnerId
        {
            get;
            set;
        }

        public int QuestId
        {
            get;
            set;
        }

        public int StepId
        {
            get;
            set;
        }

        public bool Finished
        {
            get;
            set;
        }

        public bool IsNew
        {
            get;
            set;
        }

        [Ignore]
        public List<QuestObjectiveStatus> Objectives
        {
            get;
            set;
        } = new List<QuestObjectiveStatus>();

        List<QuestObjectiveStatus> IOneToManyRecord1<QuestObjectiveStatus>.ManyProperty1 => Objectives;
    }


    [TableName("characters_quests_objectives")]
    public class QuestObjectiveStatus : IJoined, IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        [Index]
        public int QuestId
        {
            get;
            set;
        }

        int IJoined.JoinedId => QuestId;

        public int ObjectiveId
        {
            get;
            set;
        }

        public bool Status
        {
            get;
            set;
        }

        public int OwnerId
        {
            get;
            set;
        }

        public int Completion
        {
            get;
            set;
        }

        public bool IsNew
        {
            get;
            set;
        }
    }
}